---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: workload
spec:
  hosts:
  - google.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
  namespace: workload
spec:
  hosts:
    - google.com
  http:
  - timeout: 2s
    route:
      - destination:
          host: google
        weight: 100
