---
apiVersion: v1
kind: Namespace
metadata:
  name: workload
  labels:
    istio-injection: "enabled"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tester
    version: latest
  name: tester
  namespace: workload
spec:
  containers:
  - args:
    - sleep
    - 120
    image: nginx
    name: tester
  restartPolicy: Always

