---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: workload
spec:
  hosts:
  - "www.google.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
  namespace: workload
spec:
  hosts:
    - "www.google.com"
  http:
  - timeout: 2s
    route:
      - destination:
          host: "www.google.com"
        weight: 100
