---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    istio-injection: "enabled"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tester
    version: latest
  name: tester
  namespace: demo
spec:
  containers:
  - name: tester
    image: nginx
  restartPolicy: Always
