apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ext-blacklines
  namespace: demo
spec:
  hosts:
  - "www.blacklines.gr"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blacklines
  namespace: demo
spec:
  hosts:
  - "*.blacklines.gr"
  tls:
  - match:
    - port: 443
      sniHosts:
      - www.blacklines.gr
    route:
    - destination:
        host: www.blacklines.gr
        port:
          number: 443
      weight: 100
